version: '3.8'

services:
  noughts-and-crosses-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: noughts-and-crosses-api
    ports:
      - "5060:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Docker
        - NOUGHTS_AND_CROSSES_API_Logging:LogLevel:Default=Information
        - NOUGHTS_AND_CROSSES_API_Logging:LogLevel:Microsoft.AspNetCore=Warning
        - NOUGHTS_AND_CROSSES_API_MongoDb:User=crossAndNoughtsRoot
        - NOUGHTS_AND_CROSSES_API_MongoDb:Password=supersecret12)auth!
        - NOUGHTS_AND_CROSSES_API_MongoDb:Database=NoughtsAndCrosses
        - NOUGHTS_AND_CROSSES_API_MongoDb:Host=noughts-and-crosses-mongo-db
        - NOUGHTS_AND_CROSSES_API_MongoDb:Port=27017
    networks:
        - crosses-and-noughts-network
    
  mongodb:
    container_name: noughts-and-crosses-mongo-db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: crossAndNoughtsRoot
      MONGO_INITDB_ROOT_PASSWORD: supersecret12)auth!
    ports:
      - "27017:27017"
    volumes:
        - crosses_and_noughts:/data/db
    networks:
        - crosses-and-noughts-network

networks:
  crosses-and-noughts-network:
      name: crosses-and-noughts-network
      
volumes:
  crosses_and_noughts:
