version: '3.8'

services:
  noughts-and-crosses-api:
    build:
      context: .
      dockerfile: ./NoughtsAndCrosses.API/Dockerfile
    container_name: noughts-and-crosses-api
    ports:
      - "5060:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Docker
        - NOUGHTS_AND_CROSSES_API_Logging:LogLevel:Default=Information
        - NOUGHTS_AND_CROSSES_API_Logging:LogLevel:Microsoft.AspNetCore=Warning
        - NOUGHTS_AND_CROSSES_API_MongoDb:User=NoughtsAndCrossesRoot
        - NOUGHTS_AND_CROSSES_API_MongoDb:Password=supersecret12)auth!
        - NOUGHTS_AND_CROSSES_API_MongoDb:Database=NoughtsAndCrosses
        - NOUGHTS_AND_CROSSES_API_MongoDb:Host=mongo-db
        - NOUGHTS_AND_CROSSES_API_MongoDb:Port=27017
    networks:
        - noughts-and-crosses-network
    
  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    environment:
      MONGODB_INITDB_ROOT_USERNAME: NoughtsAndCrossesRoot
      MONGODB_INITDB_ROOT_PASSWORD: supersecret12)auth!
    ports:
      - "27017:27017"
    volumes:
        - noughts-and-crosses:/data/db
    networks:
        - noughts-and-crosses-network

networks:
  noughts-and-crosses-network:
      name: noughts-and-crosses-network
      
volumes:
  noughts-and-crosses:
