version: '3.8'

services:    
  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    environment:
      MONGODB_INITDB_ROOT_USERNAME: noughtsAndCrossesRoot
      MONGODB_INITDB_ROOT_PASSWORD: supersecret12)auth!
    ports:
      - "27017:27017"
    volumes:
        - noughts-and-crosses:/data/db
    networks:
        - noughts-and-crosses-network

networks:
  noughts-and-crosses-network:
      name: noughts-and-crosses-network
      
volumes:
  noughts-and-crosses:
